### ISSUE TITLE
[BUG] Backwards incompatible changes after v38..., missing release notes, node16->node20 .

### ISSUE THREAD

**Issue by jayunit100** [tj-actions/changed-files#1756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

See similar reports, such as https://github.com/actions/checkout/issues/711.

- The latest release of tj-actions (v39+) require newer node versions (0.20)
- In general https://github.com/tj-actions/changed-files/releases/tag/v40.2.0 the practice is to publish release notes for breaking changes.

Thus, I am filing this as a "bug report" because... there is no release note/breaking change notification about the new requirement on node20.

### To Reproduce

1. In an environment w/ node.js 16
2. Run the changed-files action,  with any version > 0.39
3. Observe the parsing error

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

I'd expect an error message "Node 16 not supported in this version" before the action starts, or, I'd expect release notes for 0.39, 0.40, and so on about the new requirement that breaks old deployments.

### Relevant log output

```shell
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node20' is not supported...) 
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Anything else?

No.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @jayunit100, Nodejs upgrades aren't bugs, to view release notes related to major version upgrades you can visit: https://github.com/tj-actions/changed-files/releases and use the semver e.g https://github.com/tj-actions/changed-files/releases/tag/v39.0.0. 

> \[!NOTE]
> * All major releases are created with documented breaking changes.

### Major releases since v38
- https://github.com/tj-actions/changed-files/releases/tag/v40.0.0
- https://github.com/tj-actions/changed-files/releases/tag/v39.0.0
- https://github.com/tj-actions/changed-files/releases/tag/v38.0.0


If you use self hosted you can follow this guide: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

> \[!NOTE]
> * No support would be provided for the infrastructure you run this Github action as the decision is up to you.
