### ISSUE TITLE
[BUG] Project versions are mutated without warning

### ISSUE THREAD

**Issue by MattCWheeler** [tj-actions/changed-files#382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I noticed this because I had pinned to 'tj-actions/changed-files@v13.1' and things had been working well for weeks, and suddenly (as of this morning) changed files are being incorrectly filtered out by a `files` glob. 

This led me to suspect that v13.1 wasn't the same code as it was previously. I then notices that in https://github.com/tj-actions/glob/tags (a dependency of this project) nearly all of the version tags actually point to the same commit.

Did some release go very wrong?

Notably things work again with the latest version v15 (also, how is this project versioned? I would have expected v15.0.0 or similar).

### To Reproduce

Go to https://github.com/tj-actions/glob/tags.

### What OS are you seeing the problem on?

all

### Expected behavior?

Git tags are immutable.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@MattCWheeler This was an oversight on my part a change to the glob action was wrongly pushed and clobbered the existing tags.

The error introduced in previous v13.x versions was due to a missing input which has been fixed. 

We currently maintain two versioning schemes (major).(patch) version tags and semantic versions mentioned [here](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management)

The [semver](https://github.com/tj-actions/changed-files/releases/tag/v1.0.0) was introduced by error when we transitioned from [v9.x](https://github.com/tj-actions/changed-files/releases/tag/v9.3) -> [v10](https://github.com/tj-actions/changed-files/releases/tag/v10).

We've had to maintain [v1.0.0](https://github.com/tj-actions/changed-files/releases/tag/v1.0.0) -> [v5.0.0](https://github.com/tj-actions/changed-files/releases/tag/v5.0.0) which essentially points to [v10](https://github.com/tj-actions/changed-files/releases/tag/v10) -> [v15](https://github.com/tj-actions/changed-files/releases/tag/v15) respectively. This was done to prevent things like dependabot or renovate bots from detecting new releases.

The long term goal would be to transition fully to semantic versioning and major version tags but the current usage in the wild makes this challenging.
