### ISSUE TITLE
[BUG] Changed files are always missed on macOS

### ISSUE THREAD

**Issue by akihironitta** [tj-actions/changed-files#614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Changed files are not detected by `tj-actions/changed-files@v29.0.3` on `macos-11` while they are on `ubuntu-20.04` and `windows-2022`.

- Example PR: https://github.com/Lightning-AI/lightning/pull/14563
- Example job run in the above PR: https://github.com/Lightning-AI/lightning/actions/runs/3002377305
- Issue in our repo: https://github.com/Lightning-AI/lightning/issues/14564

### To Reproduce

Use the action on `macos-11`.

### What OS are you seeing the problem on?

macos-11

### Expected behavior?

All changed files are detected by the action.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
I think the source of the issue is 
<img width="425" alt="Screen Shot 2022-09-06 at 3 19 35 PM" src="https://user-images.githubusercontent.com/17484350/188741056-fba11a44-93c3-4e46-8e2f-c8428435f91f.png"> 

The [default runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) have a small amount of resources you might require [larger runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners#overview-of-larger-runners)

**Comment by akihironitta** [comment]
@jackton1 Thank you for your reply. My apologies, that's definitely what's causing this issue.
